AWSTemplateFormatVersion: "2010-09-09"
Description: RDS for  MySQL Create

Parameters:
  SystemName:
    Type: String
    Default: raisetech
    Description: System Name
  EnvName:
    Type: String
    Default: dev
    Description: Envireonmnet Name
    AllowedValues:
      - prod
      - stg
      - dev
  DBInstanceID:
    Default: raisetech-dev-rds
    Description: My database instance
    Type: String
    MinLength: "1"
    MaxLength: "63"
    # AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription:
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
  DBName:
    Default: MySQLDataBase
    Description: MySQL database
    Type: String
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DBInstanceClass:
    Default: db.t2.micro
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
    Default: "20"
    Description: The size of the database (GiB)
    Type: Number
    MinValue: "20"
    MaxValue: "30"
    ConstraintDescription: must be between 20 and 30 GiB.
  DBUsername:
    NoEcho: "true"
    Description: Username for MySQL database access
    Type: String
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: "true"
    Description: Password MySQL database access
    Type: String
    MinLength: "8"
    MaxLength: "41"
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.

Resources:
  DBSubnetGroupName:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: ap-northeast-1a and ap-northeast-1c
      SubnetIds:
        - !ImportValue DBPrivateSubnet1A
        - !ImportValue DBPrivateSubnet1C
      Tags:
        - Key: Name
          Value: !Sub "${SystemName}-${EnvName}-db-subnet-group"

  DBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBSubnetGroupName: !Ref DBSubnetGroupName
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: MySQL
      EngineVersion: 8.0.16
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !ImportValue DatabaseSecurityGroup
      MultiAZ: true
      PubliclyAccessible: false
      PreferredBackupWindow: "18:00-18:30"
      PreferredMaintenanceWindow: "sat:19:00-sat:19:30"
      AutoMinorVersionUpgrade: false
